// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jksswsbvlwgkwjedrnlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprc3N3c2J2bHdna3dqZWRybmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjcyNjcsImV4cCI6MjA2MzEwMzI2N30.eNd13tYwO66ux6SLuYzxPckLFwPre_82T5sfYRdlQsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);